@baseUrl = http://127.0.0.1:5000
# @baseUrl = https://task-manager-app.alwaysdata.net

# Tokens from login
@Admin_Access_Token = ""
@Admin_Refresh_Token = ""

# Tokens from refresh
@User_Access_Token = ""
@User_Refresh_Token = ""

### ADMIN LOGIN REQUEST ###
# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "password@1234"
}

### VARIABLE EXTRACTION ###
@Admin_Access_Token = {{login.response.body.access_token}}
@Admin_Refresh_Token = {{login.response.body.refresh_token}}


### USER LOGIN REQUEST ###
# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "alex.smith@example.com",
    "password": "password@5678"
}

### VARIABLE EXTRACTION ###
@User_Access_Token = {{login.response.body.access_token}}
@User_Refresh_Token = {{login.response.body.refresh_token}}


### GET ALL USERS REQUEST ###
# @name getAllUsers
GET {{baseUrl}}/api/users
Authorization: Bearer {{User_Access_Token}}


### GET ALL TASKS REQUEST ###
# @name getAllTasks
GET {{baseUrl}}/api/tasks
Authorization: Bearer {{User_Access_Token}}

### CREATE TASK REQUEST ###
# @name createTask
POST {{baseUrl}}/api/tasks
Content-Type: application/json
Authorization: Bearer {{Admin_Access_Token}}

{
    "title": "New Task",
    "description": "This is a new task created via API.",
    "priority_id": 1,
    "status_id": 1,
    "start_date": "2026-03-25T09:00:00",
    "due_date": "2026-03-30T10:00:00"
}

### CREATE TASK ASSIGNED TO USERS & TODOS REQUEST ###
# @name createTaskWithUsers
POST {{baseUrl}}/api/tasks
Content-Type: application/json
Authorization: Bearer {{Admin_Access_Token}}

{
    "title": "Task with users & todos",
    "description": "Test task with users and todos assigned directly in the creation request.",
    "priority_id": 1,
    "status_id": 1,
    "start_date": "2026-03-25T09:00:00",
    "due_date": "2026-03-30T10:00:00",
    "users": [2],
    "todos": ["todo 1", "todo 2", "todo 3"]
}

### GET TASKS REQUEST ###
# @name getTasks
GET {{baseUrl}}/api/tasks
Authorization: Bearer {{Admin_Access_Token}}


### REGISTER USER REQUEST ###
# @name registerUser
POST {{baseUrl}}/api/user/register
Content-Type: application/json

{
    "name": "Gordon Freeman",
    "email": "gordon.freeman@example.com",
    "password": "password@1234"
}

### REGISTER AUTH (JSON) ###
# @name registerAuthJson
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "name": "Max Payne",
    "email": "max.payne@example.com",
    "password": "password@1234"
}

### REGISTER AUTH (MULTIPART + IMAGE) ###
# @name registerAuthWithImage
POST {{baseUrl}}/api/auth/register
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name"

Alice Image
--WebAppBoundary
Content-Disposition: form-data; name="email"

alice.image@example.com
--WebAppBoundary
Content-Disposition: form-data; name="password"

password@1234
--WebAppBoundary
Content-Disposition: form-data; name="profile_image"; filename="avatar.png"
Content-Type: image/png

< me.jpg
--WebAppBoundary--


### REGISTER AUTH (MULTIPART NO IMAGE) ###
# @name registerAuthMultipartNoImage
POST {{baseUrl}}/api/auth/register
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name"

Alice NoImage
--WebAppBoundary
Content-Disposition: form-data; name="email"

alice.noimage@example.com
--WebAppBoundary
Content-Disposition: form-data; name="password"

password@1234
--WebAppBoundary--

### UPLOAD PROFILE IMAGE FOR CURRENT USER ###
# @name uploadProfileImage
POST {{baseUrl}}/api/user/image
Authorization: Bearer {{User_Access_Token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="profile_image"; filename="me.jpg"
Content-Type: image/png

< me.jpg
--WebAppBoundary--

### DELETE PROFILE IMAGE FOR CURRENT USER ###
# @name deleteProfileImage
DELETE {{baseUrl}}/api/user/image
Authorization: Bearer {{User_Access_Token}}



### FETCH ALL STATUS REQUEST ###
# @name getStatuses
GET {{baseUrl}}/api/statuses
Authorization: Bearer {{User_Access_Token}}


### FETCH ALL PRIORITIES REQUEST ###
# @name getPriorities
GET {{baseUrl}}/api/priorities
Authorization: Bearer {{User_Access_Token}}